version: '3'
services:
  dind:
    image: docker:dind
    privileged: true
    volumes:
      - /var/lib/docker
  jenkins:
    images: jenkins/jenkins:Its
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - dind
volumes:
  jenkins-data: 
